---
- hosts: all
  roles:
  - install-dependencies
  become: yes

- hosts: operator_vms
  roles:
  - kali-tools
 become: yes

- hosts: cobaltstrike
  roles:
    - cobaltstrike
  become: yes

- hosts: sliver
  roles:
    - sliver
  vars:
    - config_name: "SWIFT-RvB-S24"
  become: yes

- hosts: pwndrop
  roles:
  - pwndrop
  become: yes

# - hosts: raven
#   roles:
#     - ansible-role-docker
#     - raven