---
- name: Remove Impacket using pip
  pip:
    name: impacket
    state: absent
    extra_args: --break-system-packages

- name: Remove Impacket directory
  file:
    path: /opt/impacket
    state: absent

- name: Remove Impacket binary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /usr/bin/impacket-wmiexec
  - /usr/bin/impacket-addcomputer
  - /usr/bin/impacket-raiseChild
  - /usr/bin/impacket-getArch
  - /usr/bin/impacket-ticketer
  - /usr/bin/impacket-ticketConverter
  - /usr/bin/impacket-Get-GPPPassword
  - /usr/bin/impacket-ping6
  - /usr/bin/impacket-smbrelayx
  - /usr/bin/impacket-GetNPUsers
  - /usr/bin/impacket-getTGT
  - /usr/bin/impacket-ntfs-read
  - /usr/bin/impacket-registry-read
  - /usr/bin/impacket-mqtt_check
  - /usr/bin/impacket-dcomexec
  - /usr/bin/impacket-smbexec
  - /usr/bin/impacket-wmiquery
  - /usr/bin/impacket-smbserver
  - /usr/bin/impacket-esentutl
  - /usr/bin/impacket-netview
  - /usr/bin/impacket-rpcdump
  - /usr/bin/impacket-samrdump
  - /usr/bin/impacket-nmapAnswerMachine
  - /usr/bin/impacket-keylistattack
  - /usr/bin/impacket-ntlmrelayx
  - /usr/bin/impacket-karmaSMB
  - /usr/bin/impacket-rdp_check
  - /usr/bin/impacket-sambaPipe
  - /usr/bin/impacket-rbcd
  - /usr/bin/impacket-GetADUsers
  - /usr/bin/impacket-sniffer
  - /usr/bin/impacket-getPac
  - /usr/bin/impacket-getST                                                                                                                                                                                          
  - /usr/bin/impacket-split                                                                                                                                                                                          
  - /usr/bin/impacket-secretsdump                                                                                                                                                                                    
  - /usr/bin/impacket-atexec                                                                                                                                                                                         
  - /usr/bin/impacket-GetUserSPNs                                                                                                                                                                                    
  - /usr/bin/impacket-mssqlclient                                                                                                                                                                                    
  - /usr/bin/impacket-kintercept                                                                                                                                                                                     
  - /usr/bin/impacket-findDelegation                                                                                                                                                                                 
  - /usr/bin/impacket-dpapi                                                                                                                                                                                          
  - /usr/bin/impacket-rpcmap                                                                                                                                                                                         
  - /usr/bin/impacket-services                                                                                                                                                                                       
  - /usr/bin/impacket-smbpasswd                                                                                                                                                                                      
  - /usr/bin/impacket-psexec                                                                                                                                                                                         
  - /usr/bin/impacket-reg                                                                                                                                                                                            
  - /usr/bin/impacket-lookupsid                                                                                                                                                                                      
  - /usr/bin/impacket-ping                                                                                                                                                                                           
  - /usr/bin/impacket-smbclient                                                                                                                                                                                      
  - /usr/bin/impacket-mimikatz
  - /usr/bin/impacket-sniff
  - /usr/bin/impacket-mssqlinstance
  - /usr/bin/impacket-exchanger
  - /usr/bin/impacket-goldenPac
  - /usr/bin/impacket-machine_role
  - /usr/bin/impacket-wmipersist

- name: Clone Impacket repository
  git:
    repo: https://github.com/ThePorgs/impacket.git
    dest: /opt/impacket
    version: master

- name: Install Impacket
  community.general.pipx:
    name: /opt/impacket
    state: present

- name: Clone Ghostpack-CompiledBinaries repository
  git:
    repo: https://github.com/r3motecontrol/Ghostpack-CompiledBinaries.git
    dest: /opt/ghostpack
    version: master

- name: Clone NetExec
  git:
    repo: https://github.com/Pennyw0rth/NetExec.git
    dest: /opt/NetExec
    version: main

- name: Install NetExec
  command: pipx install .
  args:
    chdir: /opt/NetExec

- name: Make new directory for ScareCrow
  file:
    path: /opt/ScareCrow
    state: directory

- name: Obtain ScareCrow release information from GitHub API
  uri:
    url: "https://api.github.com/repos/optiv/ScareCrow/releases/latest"
    method: GET
  register: release_info

- name: Extract ScareCrow download URL
  set_fact:
    asset_url: "{{ item.browser_download_url }}"
  loop: "{{ release_info.json.assets }}"
  when: item.name == "ScareCrow_5.1_linux_amd64"

- name: Download ScareCrow binary
  get_url:
    url: "{{ asset_url }}"
    dest: /opt/ScareCrow/ScareCrow
    mode: a+x

- name: Make new directory for sliver
  file:
    path: /opt/sliver
    state: directory

- name: Obtain Sliver release information from GitHub API
  uri:
    url: "https://api.github.com/repos/BishopFox/sliver/releases/latest"
    method: GET
  register: release_info

- name: Extract Sliver client download URL
  set_fact:
    asset_url: "{{ item.browser_download_url }}"
  loop: "{{ release_info.json.assets }}"
  when: item.name == "sliver-client_linux"

- name: Download Sliver client binary
  get_url:
    url: "{{ asset_url }}"
    dest: /opt/sliver/sliver-client
    mode: a+x

- name: Extract Sliver server download URL
  set_fact:
    asset_url: "{{ item.browser_download_url }}"
  loop: "{{ release_info.json.assets }}"
  when: item.name == "sliver-server_linux"

- name: Download Sliver server binary
  get_url:
    url: "{{ asset_url }}"
    dest: /opt/sliver/sliver-server
    mode: a+x

- name: Generating Sliver configs directory
  file:
    path: /root/.sliver-client/configs
    state: directory
    recurse: yes

- name: Generating Sliver configs
  command: /opt/sliver/sliver-server operator --name root --lhost localhost --save /root/.sliver-client/configs

- name: Install Sliver disaptch
  git:
    repo: https://github.com/susMdT/sliver_dispatcher.git
    dest: /opt/sliver_dispatcher
    version: master